
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  ADMIN: 'ADMIN',
  OFFICER: 'OFFICER'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const WasteType = {
  ORGANIC: 'ORGANIC',
  INORGANIC: 'INORGANIC'
} as const

export type WasteType = (typeof WasteType)[keyof typeof WasteType]


export const NotificationType = {
  CAPACITY_FULL: 'CAPACITY_FULL'
} as const

export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType]


export const WadahType = {
  ORGANIC: 'ORGANIC',
  INORGANIC: 'INORGANIC'
} as const

export type WadahType = (typeof WadahType)[keyof typeof WadahType]
