
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CapacityLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CapacityLog
 * 
 */
export type CapacityLogModel = runtime.Types.Result.DefaultSelection<Prisma.$CapacityLogPayload>

export type AggregateCapacityLog = {
  _count: CapacityLogCountAggregateOutputType | null
  _avg: CapacityLogAvgAggregateOutputType | null
  _sum: CapacityLogSumAggregateOutputType | null
  _min: CapacityLogMinAggregateOutputType | null
  _max: CapacityLogMaxAggregateOutputType | null
}

export type CapacityLogAvgAggregateOutputType = {
  organicLevel: number | null
  inorganicLevel: number | null
}

export type CapacityLogSumAggregateOutputType = {
  organicLevel: number | null
  inorganicLevel: number | null
}

export type CapacityLogMinAggregateOutputType = {
  id: string | null
  deviceId: string | null
  organicLevel: number | null
  inorganicLevel: number | null
  recordedAt: Date | null
}

export type CapacityLogMaxAggregateOutputType = {
  id: string | null
  deviceId: string | null
  organicLevel: number | null
  inorganicLevel: number | null
  recordedAt: Date | null
}

export type CapacityLogCountAggregateOutputType = {
  id: number
  deviceId: number
  organicLevel: number
  inorganicLevel: number
  recordedAt: number
  _all: number
}


export type CapacityLogAvgAggregateInputType = {
  organicLevel?: true
  inorganicLevel?: true
}

export type CapacityLogSumAggregateInputType = {
  organicLevel?: true
  inorganicLevel?: true
}

export type CapacityLogMinAggregateInputType = {
  id?: true
  deviceId?: true
  organicLevel?: true
  inorganicLevel?: true
  recordedAt?: true
}

export type CapacityLogMaxAggregateInputType = {
  id?: true
  deviceId?: true
  organicLevel?: true
  inorganicLevel?: true
  recordedAt?: true
}

export type CapacityLogCountAggregateInputType = {
  id?: true
  deviceId?: true
  organicLevel?: true
  inorganicLevel?: true
  recordedAt?: true
  _all?: true
}

export type CapacityLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CapacityLog to aggregate.
   */
  where?: Prisma.CapacityLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CapacityLogs to fetch.
   */
  orderBy?: Prisma.CapacityLogOrderByWithRelationInput | Prisma.CapacityLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CapacityLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CapacityLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CapacityLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CapacityLogs
  **/
  _count?: true | CapacityLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CapacityLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CapacityLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CapacityLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CapacityLogMaxAggregateInputType
}

export type GetCapacityLogAggregateType<T extends CapacityLogAggregateArgs> = {
      [P in keyof T & keyof AggregateCapacityLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCapacityLog[P]>
    : Prisma.GetScalarType<T[P], AggregateCapacityLog[P]>
}




export type CapacityLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CapacityLogWhereInput
  orderBy?: Prisma.CapacityLogOrderByWithAggregationInput | Prisma.CapacityLogOrderByWithAggregationInput[]
  by: Prisma.CapacityLogScalarFieldEnum[] | Prisma.CapacityLogScalarFieldEnum
  having?: Prisma.CapacityLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CapacityLogCountAggregateInputType | true
  _avg?: CapacityLogAvgAggregateInputType
  _sum?: CapacityLogSumAggregateInputType
  _min?: CapacityLogMinAggregateInputType
  _max?: CapacityLogMaxAggregateInputType
}

export type CapacityLogGroupByOutputType = {
  id: string
  deviceId: string
  organicLevel: number
  inorganicLevel: number
  recordedAt: Date
  _count: CapacityLogCountAggregateOutputType | null
  _avg: CapacityLogAvgAggregateOutputType | null
  _sum: CapacityLogSumAggregateOutputType | null
  _min: CapacityLogMinAggregateOutputType | null
  _max: CapacityLogMaxAggregateOutputType | null
}

export type GetCapacityLogGroupByPayload<T extends CapacityLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CapacityLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CapacityLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CapacityLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CapacityLogGroupByOutputType[P]>
      }
    >
  >



export type CapacityLogWhereInput = {
  AND?: Prisma.CapacityLogWhereInput | Prisma.CapacityLogWhereInput[]
  OR?: Prisma.CapacityLogWhereInput[]
  NOT?: Prisma.CapacityLogWhereInput | Prisma.CapacityLogWhereInput[]
  id?: Prisma.StringFilter<"CapacityLog"> | string
  deviceId?: Prisma.StringFilter<"CapacityLog"> | string
  organicLevel?: Prisma.IntFilter<"CapacityLog"> | number
  inorganicLevel?: Prisma.IntFilter<"CapacityLog"> | number
  recordedAt?: Prisma.DateTimeFilter<"CapacityLog"> | Date | string
  device?: Prisma.XOR<Prisma.DeviceScalarRelationFilter, Prisma.DeviceWhereInput>
}

export type CapacityLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  organicLevel?: Prisma.SortOrder
  inorganicLevel?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
  device?: Prisma.DeviceOrderByWithRelationInput
  _relevance?: Prisma.CapacityLogOrderByRelevanceInput
}

export type CapacityLogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CapacityLogWhereInput | Prisma.CapacityLogWhereInput[]
  OR?: Prisma.CapacityLogWhereInput[]
  NOT?: Prisma.CapacityLogWhereInput | Prisma.CapacityLogWhereInput[]
  deviceId?: Prisma.StringFilter<"CapacityLog"> | string
  organicLevel?: Prisma.IntFilter<"CapacityLog"> | number
  inorganicLevel?: Prisma.IntFilter<"CapacityLog"> | number
  recordedAt?: Prisma.DateTimeFilter<"CapacityLog"> | Date | string
  device?: Prisma.XOR<Prisma.DeviceScalarRelationFilter, Prisma.DeviceWhereInput>
}, "id">

export type CapacityLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  organicLevel?: Prisma.SortOrder
  inorganicLevel?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
  _count?: Prisma.CapacityLogCountOrderByAggregateInput
  _avg?: Prisma.CapacityLogAvgOrderByAggregateInput
  _max?: Prisma.CapacityLogMaxOrderByAggregateInput
  _min?: Prisma.CapacityLogMinOrderByAggregateInput
  _sum?: Prisma.CapacityLogSumOrderByAggregateInput
}

export type CapacityLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.CapacityLogScalarWhereWithAggregatesInput | Prisma.CapacityLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.CapacityLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CapacityLogScalarWhereWithAggregatesInput | Prisma.CapacityLogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CapacityLog"> | string
  deviceId?: Prisma.StringWithAggregatesFilter<"CapacityLog"> | string
  organicLevel?: Prisma.IntWithAggregatesFilter<"CapacityLog"> | number
  inorganicLevel?: Prisma.IntWithAggregatesFilter<"CapacityLog"> | number
  recordedAt?: Prisma.DateTimeWithAggregatesFilter<"CapacityLog"> | Date | string
}

export type CapacityLogCreateInput = {
  id?: string
  organicLevel: number
  inorganicLevel: number
  recordedAt?: Date | string
  device: Prisma.DeviceCreateNestedOneWithoutCapacityLogsInput
}

export type CapacityLogUncheckedCreateInput = {
  id?: string
  deviceId: string
  organicLevel: number
  inorganicLevel: number
  recordedAt?: Date | string
}

export type CapacityLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organicLevel?: Prisma.IntFieldUpdateOperationsInput | number
  inorganicLevel?: Prisma.IntFieldUpdateOperationsInput | number
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  device?: Prisma.DeviceUpdateOneRequiredWithoutCapacityLogsNestedInput
}

export type CapacityLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  deviceId?: Prisma.StringFieldUpdateOperationsInput | string
  organicLevel?: Prisma.IntFieldUpdateOperationsInput | number
  inorganicLevel?: Prisma.IntFieldUpdateOperationsInput | number
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CapacityLogCreateManyInput = {
  id?: string
  deviceId: string
  organicLevel: number
  inorganicLevel: number
  recordedAt?: Date | string
}

export type CapacityLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organicLevel?: Prisma.IntFieldUpdateOperationsInput | number
  inorganicLevel?: Prisma.IntFieldUpdateOperationsInput | number
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CapacityLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  deviceId?: Prisma.StringFieldUpdateOperationsInput | string
  organicLevel?: Prisma.IntFieldUpdateOperationsInput | number
  inorganicLevel?: Prisma.IntFieldUpdateOperationsInput | number
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CapacityLogListRelationFilter = {
  every?: Prisma.CapacityLogWhereInput
  some?: Prisma.CapacityLogWhereInput
  none?: Prisma.CapacityLogWhereInput
}

export type CapacityLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CapacityLogOrderByRelevanceInput = {
  fields: Prisma.CapacityLogOrderByRelevanceFieldEnum | Prisma.CapacityLogOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type CapacityLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  organicLevel?: Prisma.SortOrder
  inorganicLevel?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
}

export type CapacityLogAvgOrderByAggregateInput = {
  organicLevel?: Prisma.SortOrder
  inorganicLevel?: Prisma.SortOrder
}

export type CapacityLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  organicLevel?: Prisma.SortOrder
  inorganicLevel?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
}

export type CapacityLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  organicLevel?: Prisma.SortOrder
  inorganicLevel?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
}

export type CapacityLogSumOrderByAggregateInput = {
  organicLevel?: Prisma.SortOrder
  inorganicLevel?: Prisma.SortOrder
}

export type CapacityLogCreateNestedManyWithoutDeviceInput = {
  create?: Prisma.XOR<Prisma.CapacityLogCreateWithoutDeviceInput, Prisma.CapacityLogUncheckedCreateWithoutDeviceInput> | Prisma.CapacityLogCreateWithoutDeviceInput[] | Prisma.CapacityLogUncheckedCreateWithoutDeviceInput[]
  connectOrCreate?: Prisma.CapacityLogCreateOrConnectWithoutDeviceInput | Prisma.CapacityLogCreateOrConnectWithoutDeviceInput[]
  createMany?: Prisma.CapacityLogCreateManyDeviceInputEnvelope
  connect?: Prisma.CapacityLogWhereUniqueInput | Prisma.CapacityLogWhereUniqueInput[]
}

export type CapacityLogUncheckedCreateNestedManyWithoutDeviceInput = {
  create?: Prisma.XOR<Prisma.CapacityLogCreateWithoutDeviceInput, Prisma.CapacityLogUncheckedCreateWithoutDeviceInput> | Prisma.CapacityLogCreateWithoutDeviceInput[] | Prisma.CapacityLogUncheckedCreateWithoutDeviceInput[]
  connectOrCreate?: Prisma.CapacityLogCreateOrConnectWithoutDeviceInput | Prisma.CapacityLogCreateOrConnectWithoutDeviceInput[]
  createMany?: Prisma.CapacityLogCreateManyDeviceInputEnvelope
  connect?: Prisma.CapacityLogWhereUniqueInput | Prisma.CapacityLogWhereUniqueInput[]
}

export type CapacityLogUpdateManyWithoutDeviceNestedInput = {
  create?: Prisma.XOR<Prisma.CapacityLogCreateWithoutDeviceInput, Prisma.CapacityLogUncheckedCreateWithoutDeviceInput> | Prisma.CapacityLogCreateWithoutDeviceInput[] | Prisma.CapacityLogUncheckedCreateWithoutDeviceInput[]
  connectOrCreate?: Prisma.CapacityLogCreateOrConnectWithoutDeviceInput | Prisma.CapacityLogCreateOrConnectWithoutDeviceInput[]
  upsert?: Prisma.CapacityLogUpsertWithWhereUniqueWithoutDeviceInput | Prisma.CapacityLogUpsertWithWhereUniqueWithoutDeviceInput[]
  createMany?: Prisma.CapacityLogCreateManyDeviceInputEnvelope
  set?: Prisma.CapacityLogWhereUniqueInput | Prisma.CapacityLogWhereUniqueInput[]
  disconnect?: Prisma.CapacityLogWhereUniqueInput | Prisma.CapacityLogWhereUniqueInput[]
  delete?: Prisma.CapacityLogWhereUniqueInput | Prisma.CapacityLogWhereUniqueInput[]
  connect?: Prisma.CapacityLogWhereUniqueInput | Prisma.CapacityLogWhereUniqueInput[]
  update?: Prisma.CapacityLogUpdateWithWhereUniqueWithoutDeviceInput | Prisma.CapacityLogUpdateWithWhereUniqueWithoutDeviceInput[]
  updateMany?: Prisma.CapacityLogUpdateManyWithWhereWithoutDeviceInput | Prisma.CapacityLogUpdateManyWithWhereWithoutDeviceInput[]
  deleteMany?: Prisma.CapacityLogScalarWhereInput | Prisma.CapacityLogScalarWhereInput[]
}

export type CapacityLogUncheckedUpdateManyWithoutDeviceNestedInput = {
  create?: Prisma.XOR<Prisma.CapacityLogCreateWithoutDeviceInput, Prisma.CapacityLogUncheckedCreateWithoutDeviceInput> | Prisma.CapacityLogCreateWithoutDeviceInput[] | Prisma.CapacityLogUncheckedCreateWithoutDeviceInput[]
  connectOrCreate?: Prisma.CapacityLogCreateOrConnectWithoutDeviceInput | Prisma.CapacityLogCreateOrConnectWithoutDeviceInput[]
  upsert?: Prisma.CapacityLogUpsertWithWhereUniqueWithoutDeviceInput | Prisma.CapacityLogUpsertWithWhereUniqueWithoutDeviceInput[]
  createMany?: Prisma.CapacityLogCreateManyDeviceInputEnvelope
  set?: Prisma.CapacityLogWhereUniqueInput | Prisma.CapacityLogWhereUniqueInput[]
  disconnect?: Prisma.CapacityLogWhereUniqueInput | Prisma.CapacityLogWhereUniqueInput[]
  delete?: Prisma.CapacityLogWhereUniqueInput | Prisma.CapacityLogWhereUniqueInput[]
  connect?: Prisma.CapacityLogWhereUniqueInput | Prisma.CapacityLogWhereUniqueInput[]
  update?: Prisma.CapacityLogUpdateWithWhereUniqueWithoutDeviceInput | Prisma.CapacityLogUpdateWithWhereUniqueWithoutDeviceInput[]
  updateMany?: Prisma.CapacityLogUpdateManyWithWhereWithoutDeviceInput | Prisma.CapacityLogUpdateManyWithWhereWithoutDeviceInput[]
  deleteMany?: Prisma.CapacityLogScalarWhereInput | Prisma.CapacityLogScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type CapacityLogCreateWithoutDeviceInput = {
  id?: string
  organicLevel: number
  inorganicLevel: number
  recordedAt?: Date | string
}

export type CapacityLogUncheckedCreateWithoutDeviceInput = {
  id?: string
  organicLevel: number
  inorganicLevel: number
  recordedAt?: Date | string
}

export type CapacityLogCreateOrConnectWithoutDeviceInput = {
  where: Prisma.CapacityLogWhereUniqueInput
  create: Prisma.XOR<Prisma.CapacityLogCreateWithoutDeviceInput, Prisma.CapacityLogUncheckedCreateWithoutDeviceInput>
}

export type CapacityLogCreateManyDeviceInputEnvelope = {
  data: Prisma.CapacityLogCreateManyDeviceInput | Prisma.CapacityLogCreateManyDeviceInput[]
  skipDuplicates?: boolean
}

export type CapacityLogUpsertWithWhereUniqueWithoutDeviceInput = {
  where: Prisma.CapacityLogWhereUniqueInput
  update: Prisma.XOR<Prisma.CapacityLogUpdateWithoutDeviceInput, Prisma.CapacityLogUncheckedUpdateWithoutDeviceInput>
  create: Prisma.XOR<Prisma.CapacityLogCreateWithoutDeviceInput, Prisma.CapacityLogUncheckedCreateWithoutDeviceInput>
}

export type CapacityLogUpdateWithWhereUniqueWithoutDeviceInput = {
  where: Prisma.CapacityLogWhereUniqueInput
  data: Prisma.XOR<Prisma.CapacityLogUpdateWithoutDeviceInput, Prisma.CapacityLogUncheckedUpdateWithoutDeviceInput>
}

export type CapacityLogUpdateManyWithWhereWithoutDeviceInput = {
  where: Prisma.CapacityLogScalarWhereInput
  data: Prisma.XOR<Prisma.CapacityLogUpdateManyMutationInput, Prisma.CapacityLogUncheckedUpdateManyWithoutDeviceInput>
}

export type CapacityLogScalarWhereInput = {
  AND?: Prisma.CapacityLogScalarWhereInput | Prisma.CapacityLogScalarWhereInput[]
  OR?: Prisma.CapacityLogScalarWhereInput[]
  NOT?: Prisma.CapacityLogScalarWhereInput | Prisma.CapacityLogScalarWhereInput[]
  id?: Prisma.StringFilter<"CapacityLog"> | string
  deviceId?: Prisma.StringFilter<"CapacityLog"> | string
  organicLevel?: Prisma.IntFilter<"CapacityLog"> | number
  inorganicLevel?: Prisma.IntFilter<"CapacityLog"> | number
  recordedAt?: Prisma.DateTimeFilter<"CapacityLog"> | Date | string
}

export type CapacityLogCreateManyDeviceInput = {
  id?: string
  organicLevel: number
  inorganicLevel: number
  recordedAt?: Date | string
}

export type CapacityLogUpdateWithoutDeviceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organicLevel?: Prisma.IntFieldUpdateOperationsInput | number
  inorganicLevel?: Prisma.IntFieldUpdateOperationsInput | number
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CapacityLogUncheckedUpdateWithoutDeviceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organicLevel?: Prisma.IntFieldUpdateOperationsInput | number
  inorganicLevel?: Prisma.IntFieldUpdateOperationsInput | number
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CapacityLogUncheckedUpdateManyWithoutDeviceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organicLevel?: Prisma.IntFieldUpdateOperationsInput | number
  inorganicLevel?: Prisma.IntFieldUpdateOperationsInput | number
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CapacityLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  deviceId?: boolean
  organicLevel?: boolean
  inorganicLevel?: boolean
  recordedAt?: boolean
  device?: boolean | Prisma.DeviceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["capacityLog"]>



export type CapacityLogSelectScalar = {
  id?: boolean
  deviceId?: boolean
  organicLevel?: boolean
  inorganicLevel?: boolean
  recordedAt?: boolean
}

export type CapacityLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "deviceId" | "organicLevel" | "inorganicLevel" | "recordedAt", ExtArgs["result"]["capacityLog"]>
export type CapacityLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  device?: boolean | Prisma.DeviceDefaultArgs<ExtArgs>
}

export type $CapacityLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CapacityLog"
  objects: {
    device: Prisma.$DevicePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    deviceId: string
    organicLevel: number
    inorganicLevel: number
    recordedAt: Date
  }, ExtArgs["result"]["capacityLog"]>
  composites: {}
}

export type CapacityLogGetPayload<S extends boolean | null | undefined | CapacityLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CapacityLogPayload, S>

export type CapacityLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CapacityLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CapacityLogCountAggregateInputType | true
  }

export interface CapacityLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CapacityLog'], meta: { name: 'CapacityLog' } }
  /**
   * Find zero or one CapacityLog that matches the filter.
   * @param {CapacityLogFindUniqueArgs} args - Arguments to find a CapacityLog
   * @example
   * // Get one CapacityLog
   * const capacityLog = await prisma.capacityLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CapacityLogFindUniqueArgs>(args: Prisma.SelectSubset<T, CapacityLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CapacityLogClient<runtime.Types.Result.GetResult<Prisma.$CapacityLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CapacityLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CapacityLogFindUniqueOrThrowArgs} args - Arguments to find a CapacityLog
   * @example
   * // Get one CapacityLog
   * const capacityLog = await prisma.capacityLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CapacityLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CapacityLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CapacityLogClient<runtime.Types.Result.GetResult<Prisma.$CapacityLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CapacityLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CapacityLogFindFirstArgs} args - Arguments to find a CapacityLog
   * @example
   * // Get one CapacityLog
   * const capacityLog = await prisma.capacityLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CapacityLogFindFirstArgs>(args?: Prisma.SelectSubset<T, CapacityLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__CapacityLogClient<runtime.Types.Result.GetResult<Prisma.$CapacityLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CapacityLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CapacityLogFindFirstOrThrowArgs} args - Arguments to find a CapacityLog
   * @example
   * // Get one CapacityLog
   * const capacityLog = await prisma.capacityLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CapacityLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CapacityLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CapacityLogClient<runtime.Types.Result.GetResult<Prisma.$CapacityLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CapacityLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CapacityLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CapacityLogs
   * const capacityLogs = await prisma.capacityLog.findMany()
   * 
   * // Get first 10 CapacityLogs
   * const capacityLogs = await prisma.capacityLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const capacityLogWithIdOnly = await prisma.capacityLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CapacityLogFindManyArgs>(args?: Prisma.SelectSubset<T, CapacityLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CapacityLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CapacityLog.
   * @param {CapacityLogCreateArgs} args - Arguments to create a CapacityLog.
   * @example
   * // Create one CapacityLog
   * const CapacityLog = await prisma.capacityLog.create({
   *   data: {
   *     // ... data to create a CapacityLog
   *   }
   * })
   * 
   */
  create<T extends CapacityLogCreateArgs>(args: Prisma.SelectSubset<T, CapacityLogCreateArgs<ExtArgs>>): Prisma.Prisma__CapacityLogClient<runtime.Types.Result.GetResult<Prisma.$CapacityLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CapacityLogs.
   * @param {CapacityLogCreateManyArgs} args - Arguments to create many CapacityLogs.
   * @example
   * // Create many CapacityLogs
   * const capacityLog = await prisma.capacityLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CapacityLogCreateManyArgs>(args?: Prisma.SelectSubset<T, CapacityLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a CapacityLog.
   * @param {CapacityLogDeleteArgs} args - Arguments to delete one CapacityLog.
   * @example
   * // Delete one CapacityLog
   * const CapacityLog = await prisma.capacityLog.delete({
   *   where: {
   *     // ... filter to delete one CapacityLog
   *   }
   * })
   * 
   */
  delete<T extends CapacityLogDeleteArgs>(args: Prisma.SelectSubset<T, CapacityLogDeleteArgs<ExtArgs>>): Prisma.Prisma__CapacityLogClient<runtime.Types.Result.GetResult<Prisma.$CapacityLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CapacityLog.
   * @param {CapacityLogUpdateArgs} args - Arguments to update one CapacityLog.
   * @example
   * // Update one CapacityLog
   * const capacityLog = await prisma.capacityLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CapacityLogUpdateArgs>(args: Prisma.SelectSubset<T, CapacityLogUpdateArgs<ExtArgs>>): Prisma.Prisma__CapacityLogClient<runtime.Types.Result.GetResult<Prisma.$CapacityLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CapacityLogs.
   * @param {CapacityLogDeleteManyArgs} args - Arguments to filter CapacityLogs to delete.
   * @example
   * // Delete a few CapacityLogs
   * const { count } = await prisma.capacityLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CapacityLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, CapacityLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CapacityLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CapacityLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CapacityLogs
   * const capacityLog = await prisma.capacityLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CapacityLogUpdateManyArgs>(args: Prisma.SelectSubset<T, CapacityLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one CapacityLog.
   * @param {CapacityLogUpsertArgs} args - Arguments to update or create a CapacityLog.
   * @example
   * // Update or create a CapacityLog
   * const capacityLog = await prisma.capacityLog.upsert({
   *   create: {
   *     // ... data to create a CapacityLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CapacityLog we want to update
   *   }
   * })
   */
  upsert<T extends CapacityLogUpsertArgs>(args: Prisma.SelectSubset<T, CapacityLogUpsertArgs<ExtArgs>>): Prisma.Prisma__CapacityLogClient<runtime.Types.Result.GetResult<Prisma.$CapacityLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CapacityLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CapacityLogCountArgs} args - Arguments to filter CapacityLogs to count.
   * @example
   * // Count the number of CapacityLogs
   * const count = await prisma.capacityLog.count({
   *   where: {
   *     // ... the filter for the CapacityLogs we want to count
   *   }
   * })
  **/
  count<T extends CapacityLogCountArgs>(
    args?: Prisma.Subset<T, CapacityLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CapacityLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CapacityLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CapacityLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CapacityLogAggregateArgs>(args: Prisma.Subset<T, CapacityLogAggregateArgs>): Prisma.PrismaPromise<GetCapacityLogAggregateType<T>>

  /**
   * Group by CapacityLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CapacityLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CapacityLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CapacityLogGroupByArgs['orderBy'] }
      : { orderBy?: CapacityLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CapacityLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCapacityLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CapacityLog model
 */
readonly fields: CapacityLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CapacityLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CapacityLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  device<T extends Prisma.DeviceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DeviceDefaultArgs<ExtArgs>>): Prisma.Prisma__DeviceClient<runtime.Types.Result.GetResult<Prisma.$DevicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CapacityLog model
 */
export interface CapacityLogFieldRefs {
  readonly id: Prisma.FieldRef<"CapacityLog", 'String'>
  readonly deviceId: Prisma.FieldRef<"CapacityLog", 'String'>
  readonly organicLevel: Prisma.FieldRef<"CapacityLog", 'Int'>
  readonly inorganicLevel: Prisma.FieldRef<"CapacityLog", 'Int'>
  readonly recordedAt: Prisma.FieldRef<"CapacityLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CapacityLog findUnique
 */
export type CapacityLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CapacityLog
   */
  select?: Prisma.CapacityLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CapacityLog
   */
  omit?: Prisma.CapacityLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CapacityLogInclude<ExtArgs> | null
  /**
   * Filter, which CapacityLog to fetch.
   */
  where: Prisma.CapacityLogWhereUniqueInput
}

/**
 * CapacityLog findUniqueOrThrow
 */
export type CapacityLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CapacityLog
   */
  select?: Prisma.CapacityLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CapacityLog
   */
  omit?: Prisma.CapacityLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CapacityLogInclude<ExtArgs> | null
  /**
   * Filter, which CapacityLog to fetch.
   */
  where: Prisma.CapacityLogWhereUniqueInput
}

/**
 * CapacityLog findFirst
 */
export type CapacityLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CapacityLog
   */
  select?: Prisma.CapacityLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CapacityLog
   */
  omit?: Prisma.CapacityLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CapacityLogInclude<ExtArgs> | null
  /**
   * Filter, which CapacityLog to fetch.
   */
  where?: Prisma.CapacityLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CapacityLogs to fetch.
   */
  orderBy?: Prisma.CapacityLogOrderByWithRelationInput | Prisma.CapacityLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CapacityLogs.
   */
  cursor?: Prisma.CapacityLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CapacityLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CapacityLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CapacityLogs.
   */
  distinct?: Prisma.CapacityLogScalarFieldEnum | Prisma.CapacityLogScalarFieldEnum[]
}

/**
 * CapacityLog findFirstOrThrow
 */
export type CapacityLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CapacityLog
   */
  select?: Prisma.CapacityLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CapacityLog
   */
  omit?: Prisma.CapacityLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CapacityLogInclude<ExtArgs> | null
  /**
   * Filter, which CapacityLog to fetch.
   */
  where?: Prisma.CapacityLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CapacityLogs to fetch.
   */
  orderBy?: Prisma.CapacityLogOrderByWithRelationInput | Prisma.CapacityLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CapacityLogs.
   */
  cursor?: Prisma.CapacityLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CapacityLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CapacityLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CapacityLogs.
   */
  distinct?: Prisma.CapacityLogScalarFieldEnum | Prisma.CapacityLogScalarFieldEnum[]
}

/**
 * CapacityLog findMany
 */
export type CapacityLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CapacityLog
   */
  select?: Prisma.CapacityLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CapacityLog
   */
  omit?: Prisma.CapacityLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CapacityLogInclude<ExtArgs> | null
  /**
   * Filter, which CapacityLogs to fetch.
   */
  where?: Prisma.CapacityLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CapacityLogs to fetch.
   */
  orderBy?: Prisma.CapacityLogOrderByWithRelationInput | Prisma.CapacityLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CapacityLogs.
   */
  cursor?: Prisma.CapacityLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CapacityLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CapacityLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CapacityLogs.
   */
  distinct?: Prisma.CapacityLogScalarFieldEnum | Prisma.CapacityLogScalarFieldEnum[]
}

/**
 * CapacityLog create
 */
export type CapacityLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CapacityLog
   */
  select?: Prisma.CapacityLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CapacityLog
   */
  omit?: Prisma.CapacityLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CapacityLogInclude<ExtArgs> | null
  /**
   * The data needed to create a CapacityLog.
   */
  data: Prisma.XOR<Prisma.CapacityLogCreateInput, Prisma.CapacityLogUncheckedCreateInput>
}

/**
 * CapacityLog createMany
 */
export type CapacityLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CapacityLogs.
   */
  data: Prisma.CapacityLogCreateManyInput | Prisma.CapacityLogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CapacityLog update
 */
export type CapacityLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CapacityLog
   */
  select?: Prisma.CapacityLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CapacityLog
   */
  omit?: Prisma.CapacityLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CapacityLogInclude<ExtArgs> | null
  /**
   * The data needed to update a CapacityLog.
   */
  data: Prisma.XOR<Prisma.CapacityLogUpdateInput, Prisma.CapacityLogUncheckedUpdateInput>
  /**
   * Choose, which CapacityLog to update.
   */
  where: Prisma.CapacityLogWhereUniqueInput
}

/**
 * CapacityLog updateMany
 */
export type CapacityLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CapacityLogs.
   */
  data: Prisma.XOR<Prisma.CapacityLogUpdateManyMutationInput, Prisma.CapacityLogUncheckedUpdateManyInput>
  /**
   * Filter which CapacityLogs to update
   */
  where?: Prisma.CapacityLogWhereInput
  /**
   * Limit how many CapacityLogs to update.
   */
  limit?: number
}

/**
 * CapacityLog upsert
 */
export type CapacityLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CapacityLog
   */
  select?: Prisma.CapacityLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CapacityLog
   */
  omit?: Prisma.CapacityLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CapacityLogInclude<ExtArgs> | null
  /**
   * The filter to search for the CapacityLog to update in case it exists.
   */
  where: Prisma.CapacityLogWhereUniqueInput
  /**
   * In case the CapacityLog found by the `where` argument doesn't exist, create a new CapacityLog with this data.
   */
  create: Prisma.XOR<Prisma.CapacityLogCreateInput, Prisma.CapacityLogUncheckedCreateInput>
  /**
   * In case the CapacityLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CapacityLogUpdateInput, Prisma.CapacityLogUncheckedUpdateInput>
}

/**
 * CapacityLog delete
 */
export type CapacityLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CapacityLog
   */
  select?: Prisma.CapacityLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CapacityLog
   */
  omit?: Prisma.CapacityLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CapacityLogInclude<ExtArgs> | null
  /**
   * Filter which CapacityLog to delete.
   */
  where: Prisma.CapacityLogWhereUniqueInput
}

/**
 * CapacityLog deleteMany
 */
export type CapacityLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CapacityLogs to delete
   */
  where?: Prisma.CapacityLogWhereInput
  /**
   * Limit how many CapacityLogs to delete.
   */
  limit?: number
}

/**
 * CapacityLog without action
 */
export type CapacityLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CapacityLog
   */
  select?: Prisma.CapacityLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CapacityLog
   */
  omit?: Prisma.CapacityLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CapacityLogInclude<ExtArgs> | null
}
