
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WasteEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model WasteEvent
 * 
 */
export type WasteEventModel = runtime.Types.Result.DefaultSelection<Prisma.$WasteEventPayload>

export type AggregateWasteEvent = {
  _count: WasteEventCountAggregateOutputType | null
  _avg: WasteEventAvgAggregateOutputType | null
  _sum: WasteEventSumAggregateOutputType | null
  _min: WasteEventMinAggregateOutputType | null
  _max: WasteEventMaxAggregateOutputType | null
}

export type WasteEventAvgAggregateOutputType = {
  moistureValue: number | null
}

export type WasteEventSumAggregateOutputType = {
  moistureValue: number | null
}

export type WasteEventMinAggregateOutputType = {
  id: string | null
  deviceId: string | null
  wasteType: $Enums.WasteType | null
  moistureValue: number | null
  detectedAt: Date | null
}

export type WasteEventMaxAggregateOutputType = {
  id: string | null
  deviceId: string | null
  wasteType: $Enums.WasteType | null
  moistureValue: number | null
  detectedAt: Date | null
}

export type WasteEventCountAggregateOutputType = {
  id: number
  deviceId: number
  wasteType: number
  moistureValue: number
  detectedAt: number
  _all: number
}


export type WasteEventAvgAggregateInputType = {
  moistureValue?: true
}

export type WasteEventSumAggregateInputType = {
  moistureValue?: true
}

export type WasteEventMinAggregateInputType = {
  id?: true
  deviceId?: true
  wasteType?: true
  moistureValue?: true
  detectedAt?: true
}

export type WasteEventMaxAggregateInputType = {
  id?: true
  deviceId?: true
  wasteType?: true
  moistureValue?: true
  detectedAt?: true
}

export type WasteEventCountAggregateInputType = {
  id?: true
  deviceId?: true
  wasteType?: true
  moistureValue?: true
  detectedAt?: true
  _all?: true
}

export type WasteEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WasteEvent to aggregate.
   */
  where?: Prisma.WasteEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WasteEvents to fetch.
   */
  orderBy?: Prisma.WasteEventOrderByWithRelationInput | Prisma.WasteEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WasteEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WasteEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WasteEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WasteEvents
  **/
  _count?: true | WasteEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WasteEventAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WasteEventSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WasteEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WasteEventMaxAggregateInputType
}

export type GetWasteEventAggregateType<T extends WasteEventAggregateArgs> = {
      [P in keyof T & keyof AggregateWasteEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWasteEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateWasteEvent[P]>
}




export type WasteEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WasteEventWhereInput
  orderBy?: Prisma.WasteEventOrderByWithAggregationInput | Prisma.WasteEventOrderByWithAggregationInput[]
  by: Prisma.WasteEventScalarFieldEnum[] | Prisma.WasteEventScalarFieldEnum
  having?: Prisma.WasteEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WasteEventCountAggregateInputType | true
  _avg?: WasteEventAvgAggregateInputType
  _sum?: WasteEventSumAggregateInputType
  _min?: WasteEventMinAggregateInputType
  _max?: WasteEventMaxAggregateInputType
}

export type WasteEventGroupByOutputType = {
  id: string
  deviceId: string
  wasteType: $Enums.WasteType
  moistureValue: number
  detectedAt: Date
  _count: WasteEventCountAggregateOutputType | null
  _avg: WasteEventAvgAggregateOutputType | null
  _sum: WasteEventSumAggregateOutputType | null
  _min: WasteEventMinAggregateOutputType | null
  _max: WasteEventMaxAggregateOutputType | null
}

export type GetWasteEventGroupByPayload<T extends WasteEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WasteEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WasteEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WasteEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WasteEventGroupByOutputType[P]>
      }
    >
  >



export type WasteEventWhereInput = {
  AND?: Prisma.WasteEventWhereInput | Prisma.WasteEventWhereInput[]
  OR?: Prisma.WasteEventWhereInput[]
  NOT?: Prisma.WasteEventWhereInput | Prisma.WasteEventWhereInput[]
  id?: Prisma.StringFilter<"WasteEvent"> | string
  deviceId?: Prisma.StringFilter<"WasteEvent"> | string
  wasteType?: Prisma.EnumWasteTypeFilter<"WasteEvent"> | $Enums.WasteType
  moistureValue?: Prisma.FloatFilter<"WasteEvent"> | number
  detectedAt?: Prisma.DateTimeFilter<"WasteEvent"> | Date | string
  device?: Prisma.XOR<Prisma.DeviceScalarRelationFilter, Prisma.DeviceWhereInput>
}

export type WasteEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  wasteType?: Prisma.SortOrder
  moistureValue?: Prisma.SortOrder
  detectedAt?: Prisma.SortOrder
  device?: Prisma.DeviceOrderByWithRelationInput
  _relevance?: Prisma.WasteEventOrderByRelevanceInput
}

export type WasteEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WasteEventWhereInput | Prisma.WasteEventWhereInput[]
  OR?: Prisma.WasteEventWhereInput[]
  NOT?: Prisma.WasteEventWhereInput | Prisma.WasteEventWhereInput[]
  deviceId?: Prisma.StringFilter<"WasteEvent"> | string
  wasteType?: Prisma.EnumWasteTypeFilter<"WasteEvent"> | $Enums.WasteType
  moistureValue?: Prisma.FloatFilter<"WasteEvent"> | number
  detectedAt?: Prisma.DateTimeFilter<"WasteEvent"> | Date | string
  device?: Prisma.XOR<Prisma.DeviceScalarRelationFilter, Prisma.DeviceWhereInput>
}, "id">

export type WasteEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  wasteType?: Prisma.SortOrder
  moistureValue?: Prisma.SortOrder
  detectedAt?: Prisma.SortOrder
  _count?: Prisma.WasteEventCountOrderByAggregateInput
  _avg?: Prisma.WasteEventAvgOrderByAggregateInput
  _max?: Prisma.WasteEventMaxOrderByAggregateInput
  _min?: Prisma.WasteEventMinOrderByAggregateInput
  _sum?: Prisma.WasteEventSumOrderByAggregateInput
}

export type WasteEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.WasteEventScalarWhereWithAggregatesInput | Prisma.WasteEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.WasteEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WasteEventScalarWhereWithAggregatesInput | Prisma.WasteEventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WasteEvent"> | string
  deviceId?: Prisma.StringWithAggregatesFilter<"WasteEvent"> | string
  wasteType?: Prisma.EnumWasteTypeWithAggregatesFilter<"WasteEvent"> | $Enums.WasteType
  moistureValue?: Prisma.FloatWithAggregatesFilter<"WasteEvent"> | number
  detectedAt?: Prisma.DateTimeWithAggregatesFilter<"WasteEvent"> | Date | string
}

export type WasteEventCreateInput = {
  id?: string
  wasteType: $Enums.WasteType
  moistureValue: number
  detectedAt?: Date | string
  device: Prisma.DeviceCreateNestedOneWithoutWasteEventsInput
}

export type WasteEventUncheckedCreateInput = {
  id?: string
  deviceId: string
  wasteType: $Enums.WasteType
  moistureValue: number
  detectedAt?: Date | string
}

export type WasteEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wasteType?: Prisma.EnumWasteTypeFieldUpdateOperationsInput | $Enums.WasteType
  moistureValue?: Prisma.FloatFieldUpdateOperationsInput | number
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  device?: Prisma.DeviceUpdateOneRequiredWithoutWasteEventsNestedInput
}

export type WasteEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  deviceId?: Prisma.StringFieldUpdateOperationsInput | string
  wasteType?: Prisma.EnumWasteTypeFieldUpdateOperationsInput | $Enums.WasteType
  moistureValue?: Prisma.FloatFieldUpdateOperationsInput | number
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WasteEventCreateManyInput = {
  id?: string
  deviceId: string
  wasteType: $Enums.WasteType
  moistureValue: number
  detectedAt?: Date | string
}

export type WasteEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wasteType?: Prisma.EnumWasteTypeFieldUpdateOperationsInput | $Enums.WasteType
  moistureValue?: Prisma.FloatFieldUpdateOperationsInput | number
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WasteEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  deviceId?: Prisma.StringFieldUpdateOperationsInput | string
  wasteType?: Prisma.EnumWasteTypeFieldUpdateOperationsInput | $Enums.WasteType
  moistureValue?: Prisma.FloatFieldUpdateOperationsInput | number
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WasteEventListRelationFilter = {
  every?: Prisma.WasteEventWhereInput
  some?: Prisma.WasteEventWhereInput
  none?: Prisma.WasteEventWhereInput
}

export type WasteEventOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WasteEventOrderByRelevanceInput = {
  fields: Prisma.WasteEventOrderByRelevanceFieldEnum | Prisma.WasteEventOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type WasteEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  wasteType?: Prisma.SortOrder
  moistureValue?: Prisma.SortOrder
  detectedAt?: Prisma.SortOrder
}

export type WasteEventAvgOrderByAggregateInput = {
  moistureValue?: Prisma.SortOrder
}

export type WasteEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  wasteType?: Prisma.SortOrder
  moistureValue?: Prisma.SortOrder
  detectedAt?: Prisma.SortOrder
}

export type WasteEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
  wasteType?: Prisma.SortOrder
  moistureValue?: Prisma.SortOrder
  detectedAt?: Prisma.SortOrder
}

export type WasteEventSumOrderByAggregateInput = {
  moistureValue?: Prisma.SortOrder
}

export type WasteEventCreateNestedManyWithoutDeviceInput = {
  create?: Prisma.XOR<Prisma.WasteEventCreateWithoutDeviceInput, Prisma.WasteEventUncheckedCreateWithoutDeviceInput> | Prisma.WasteEventCreateWithoutDeviceInput[] | Prisma.WasteEventUncheckedCreateWithoutDeviceInput[]
  connectOrCreate?: Prisma.WasteEventCreateOrConnectWithoutDeviceInput | Prisma.WasteEventCreateOrConnectWithoutDeviceInput[]
  createMany?: Prisma.WasteEventCreateManyDeviceInputEnvelope
  connect?: Prisma.WasteEventWhereUniqueInput | Prisma.WasteEventWhereUniqueInput[]
}

export type WasteEventUncheckedCreateNestedManyWithoutDeviceInput = {
  create?: Prisma.XOR<Prisma.WasteEventCreateWithoutDeviceInput, Prisma.WasteEventUncheckedCreateWithoutDeviceInput> | Prisma.WasteEventCreateWithoutDeviceInput[] | Prisma.WasteEventUncheckedCreateWithoutDeviceInput[]
  connectOrCreate?: Prisma.WasteEventCreateOrConnectWithoutDeviceInput | Prisma.WasteEventCreateOrConnectWithoutDeviceInput[]
  createMany?: Prisma.WasteEventCreateManyDeviceInputEnvelope
  connect?: Prisma.WasteEventWhereUniqueInput | Prisma.WasteEventWhereUniqueInput[]
}

export type WasteEventUpdateManyWithoutDeviceNestedInput = {
  create?: Prisma.XOR<Prisma.WasteEventCreateWithoutDeviceInput, Prisma.WasteEventUncheckedCreateWithoutDeviceInput> | Prisma.WasteEventCreateWithoutDeviceInput[] | Prisma.WasteEventUncheckedCreateWithoutDeviceInput[]
  connectOrCreate?: Prisma.WasteEventCreateOrConnectWithoutDeviceInput | Prisma.WasteEventCreateOrConnectWithoutDeviceInput[]
  upsert?: Prisma.WasteEventUpsertWithWhereUniqueWithoutDeviceInput | Prisma.WasteEventUpsertWithWhereUniqueWithoutDeviceInput[]
  createMany?: Prisma.WasteEventCreateManyDeviceInputEnvelope
  set?: Prisma.WasteEventWhereUniqueInput | Prisma.WasteEventWhereUniqueInput[]
  disconnect?: Prisma.WasteEventWhereUniqueInput | Prisma.WasteEventWhereUniqueInput[]
  delete?: Prisma.WasteEventWhereUniqueInput | Prisma.WasteEventWhereUniqueInput[]
  connect?: Prisma.WasteEventWhereUniqueInput | Prisma.WasteEventWhereUniqueInput[]
  update?: Prisma.WasteEventUpdateWithWhereUniqueWithoutDeviceInput | Prisma.WasteEventUpdateWithWhereUniqueWithoutDeviceInput[]
  updateMany?: Prisma.WasteEventUpdateManyWithWhereWithoutDeviceInput | Prisma.WasteEventUpdateManyWithWhereWithoutDeviceInput[]
  deleteMany?: Prisma.WasteEventScalarWhereInput | Prisma.WasteEventScalarWhereInput[]
}

export type WasteEventUncheckedUpdateManyWithoutDeviceNestedInput = {
  create?: Prisma.XOR<Prisma.WasteEventCreateWithoutDeviceInput, Prisma.WasteEventUncheckedCreateWithoutDeviceInput> | Prisma.WasteEventCreateWithoutDeviceInput[] | Prisma.WasteEventUncheckedCreateWithoutDeviceInput[]
  connectOrCreate?: Prisma.WasteEventCreateOrConnectWithoutDeviceInput | Prisma.WasteEventCreateOrConnectWithoutDeviceInput[]
  upsert?: Prisma.WasteEventUpsertWithWhereUniqueWithoutDeviceInput | Prisma.WasteEventUpsertWithWhereUniqueWithoutDeviceInput[]
  createMany?: Prisma.WasteEventCreateManyDeviceInputEnvelope
  set?: Prisma.WasteEventWhereUniqueInput | Prisma.WasteEventWhereUniqueInput[]
  disconnect?: Prisma.WasteEventWhereUniqueInput | Prisma.WasteEventWhereUniqueInput[]
  delete?: Prisma.WasteEventWhereUniqueInput | Prisma.WasteEventWhereUniqueInput[]
  connect?: Prisma.WasteEventWhereUniqueInput | Prisma.WasteEventWhereUniqueInput[]
  update?: Prisma.WasteEventUpdateWithWhereUniqueWithoutDeviceInput | Prisma.WasteEventUpdateWithWhereUniqueWithoutDeviceInput[]
  updateMany?: Prisma.WasteEventUpdateManyWithWhereWithoutDeviceInput | Prisma.WasteEventUpdateManyWithWhereWithoutDeviceInput[]
  deleteMany?: Prisma.WasteEventScalarWhereInput | Prisma.WasteEventScalarWhereInput[]
}

export type EnumWasteTypeFieldUpdateOperationsInput = {
  set?: $Enums.WasteType
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type WasteEventCreateWithoutDeviceInput = {
  id?: string
  wasteType: $Enums.WasteType
  moistureValue: number
  detectedAt?: Date | string
}

export type WasteEventUncheckedCreateWithoutDeviceInput = {
  id?: string
  wasteType: $Enums.WasteType
  moistureValue: number
  detectedAt?: Date | string
}

export type WasteEventCreateOrConnectWithoutDeviceInput = {
  where: Prisma.WasteEventWhereUniqueInput
  create: Prisma.XOR<Prisma.WasteEventCreateWithoutDeviceInput, Prisma.WasteEventUncheckedCreateWithoutDeviceInput>
}

export type WasteEventCreateManyDeviceInputEnvelope = {
  data: Prisma.WasteEventCreateManyDeviceInput | Prisma.WasteEventCreateManyDeviceInput[]
  skipDuplicates?: boolean
}

export type WasteEventUpsertWithWhereUniqueWithoutDeviceInput = {
  where: Prisma.WasteEventWhereUniqueInput
  update: Prisma.XOR<Prisma.WasteEventUpdateWithoutDeviceInput, Prisma.WasteEventUncheckedUpdateWithoutDeviceInput>
  create: Prisma.XOR<Prisma.WasteEventCreateWithoutDeviceInput, Prisma.WasteEventUncheckedCreateWithoutDeviceInput>
}

export type WasteEventUpdateWithWhereUniqueWithoutDeviceInput = {
  where: Prisma.WasteEventWhereUniqueInput
  data: Prisma.XOR<Prisma.WasteEventUpdateWithoutDeviceInput, Prisma.WasteEventUncheckedUpdateWithoutDeviceInput>
}

export type WasteEventUpdateManyWithWhereWithoutDeviceInput = {
  where: Prisma.WasteEventScalarWhereInput
  data: Prisma.XOR<Prisma.WasteEventUpdateManyMutationInput, Prisma.WasteEventUncheckedUpdateManyWithoutDeviceInput>
}

export type WasteEventScalarWhereInput = {
  AND?: Prisma.WasteEventScalarWhereInput | Prisma.WasteEventScalarWhereInput[]
  OR?: Prisma.WasteEventScalarWhereInput[]
  NOT?: Prisma.WasteEventScalarWhereInput | Prisma.WasteEventScalarWhereInput[]
  id?: Prisma.StringFilter<"WasteEvent"> | string
  deviceId?: Prisma.StringFilter<"WasteEvent"> | string
  wasteType?: Prisma.EnumWasteTypeFilter<"WasteEvent"> | $Enums.WasteType
  moistureValue?: Prisma.FloatFilter<"WasteEvent"> | number
  detectedAt?: Prisma.DateTimeFilter<"WasteEvent"> | Date | string
}

export type WasteEventCreateManyDeviceInput = {
  id?: string
  wasteType: $Enums.WasteType
  moistureValue: number
  detectedAt?: Date | string
}

export type WasteEventUpdateWithoutDeviceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wasteType?: Prisma.EnumWasteTypeFieldUpdateOperationsInput | $Enums.WasteType
  moistureValue?: Prisma.FloatFieldUpdateOperationsInput | number
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WasteEventUncheckedUpdateWithoutDeviceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wasteType?: Prisma.EnumWasteTypeFieldUpdateOperationsInput | $Enums.WasteType
  moistureValue?: Prisma.FloatFieldUpdateOperationsInput | number
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WasteEventUncheckedUpdateManyWithoutDeviceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wasteType?: Prisma.EnumWasteTypeFieldUpdateOperationsInput | $Enums.WasteType
  moistureValue?: Prisma.FloatFieldUpdateOperationsInput | number
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type WasteEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  deviceId?: boolean
  wasteType?: boolean
  moistureValue?: boolean
  detectedAt?: boolean
  device?: boolean | Prisma.DeviceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wasteEvent"]>



export type WasteEventSelectScalar = {
  id?: boolean
  deviceId?: boolean
  wasteType?: boolean
  moistureValue?: boolean
  detectedAt?: boolean
}

export type WasteEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "deviceId" | "wasteType" | "moistureValue" | "detectedAt", ExtArgs["result"]["wasteEvent"]>
export type WasteEventInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  device?: boolean | Prisma.DeviceDefaultArgs<ExtArgs>
}

export type $WasteEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WasteEvent"
  objects: {
    device: Prisma.$DevicePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    deviceId: string
    wasteType: $Enums.WasteType
    moistureValue: number
    detectedAt: Date
  }, ExtArgs["result"]["wasteEvent"]>
  composites: {}
}

export type WasteEventGetPayload<S extends boolean | null | undefined | WasteEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WasteEventPayload, S>

export type WasteEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WasteEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WasteEventCountAggregateInputType | true
  }

export interface WasteEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WasteEvent'], meta: { name: 'WasteEvent' } }
  /**
   * Find zero or one WasteEvent that matches the filter.
   * @param {WasteEventFindUniqueArgs} args - Arguments to find a WasteEvent
   * @example
   * // Get one WasteEvent
   * const wasteEvent = await prisma.wasteEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WasteEventFindUniqueArgs>(args: Prisma.SelectSubset<T, WasteEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WasteEventClient<runtime.Types.Result.GetResult<Prisma.$WasteEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WasteEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WasteEventFindUniqueOrThrowArgs} args - Arguments to find a WasteEvent
   * @example
   * // Get one WasteEvent
   * const wasteEvent = await prisma.wasteEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WasteEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WasteEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WasteEventClient<runtime.Types.Result.GetResult<Prisma.$WasteEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WasteEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WasteEventFindFirstArgs} args - Arguments to find a WasteEvent
   * @example
   * // Get one WasteEvent
   * const wasteEvent = await prisma.wasteEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WasteEventFindFirstArgs>(args?: Prisma.SelectSubset<T, WasteEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__WasteEventClient<runtime.Types.Result.GetResult<Prisma.$WasteEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WasteEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WasteEventFindFirstOrThrowArgs} args - Arguments to find a WasteEvent
   * @example
   * // Get one WasteEvent
   * const wasteEvent = await prisma.wasteEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WasteEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WasteEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WasteEventClient<runtime.Types.Result.GetResult<Prisma.$WasteEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WasteEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WasteEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WasteEvents
   * const wasteEvents = await prisma.wasteEvent.findMany()
   * 
   * // Get first 10 WasteEvents
   * const wasteEvents = await prisma.wasteEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const wasteEventWithIdOnly = await prisma.wasteEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WasteEventFindManyArgs>(args?: Prisma.SelectSubset<T, WasteEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WasteEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WasteEvent.
   * @param {WasteEventCreateArgs} args - Arguments to create a WasteEvent.
   * @example
   * // Create one WasteEvent
   * const WasteEvent = await prisma.wasteEvent.create({
   *   data: {
   *     // ... data to create a WasteEvent
   *   }
   * })
   * 
   */
  create<T extends WasteEventCreateArgs>(args: Prisma.SelectSubset<T, WasteEventCreateArgs<ExtArgs>>): Prisma.Prisma__WasteEventClient<runtime.Types.Result.GetResult<Prisma.$WasteEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WasteEvents.
   * @param {WasteEventCreateManyArgs} args - Arguments to create many WasteEvents.
   * @example
   * // Create many WasteEvents
   * const wasteEvent = await prisma.wasteEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WasteEventCreateManyArgs>(args?: Prisma.SelectSubset<T, WasteEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a WasteEvent.
   * @param {WasteEventDeleteArgs} args - Arguments to delete one WasteEvent.
   * @example
   * // Delete one WasteEvent
   * const WasteEvent = await prisma.wasteEvent.delete({
   *   where: {
   *     // ... filter to delete one WasteEvent
   *   }
   * })
   * 
   */
  delete<T extends WasteEventDeleteArgs>(args: Prisma.SelectSubset<T, WasteEventDeleteArgs<ExtArgs>>): Prisma.Prisma__WasteEventClient<runtime.Types.Result.GetResult<Prisma.$WasteEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WasteEvent.
   * @param {WasteEventUpdateArgs} args - Arguments to update one WasteEvent.
   * @example
   * // Update one WasteEvent
   * const wasteEvent = await prisma.wasteEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WasteEventUpdateArgs>(args: Prisma.SelectSubset<T, WasteEventUpdateArgs<ExtArgs>>): Prisma.Prisma__WasteEventClient<runtime.Types.Result.GetResult<Prisma.$WasteEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WasteEvents.
   * @param {WasteEventDeleteManyArgs} args - Arguments to filter WasteEvents to delete.
   * @example
   * // Delete a few WasteEvents
   * const { count } = await prisma.wasteEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WasteEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, WasteEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WasteEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WasteEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WasteEvents
   * const wasteEvent = await prisma.wasteEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WasteEventUpdateManyArgs>(args: Prisma.SelectSubset<T, WasteEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one WasteEvent.
   * @param {WasteEventUpsertArgs} args - Arguments to update or create a WasteEvent.
   * @example
   * // Update or create a WasteEvent
   * const wasteEvent = await prisma.wasteEvent.upsert({
   *   create: {
   *     // ... data to create a WasteEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WasteEvent we want to update
   *   }
   * })
   */
  upsert<T extends WasteEventUpsertArgs>(args: Prisma.SelectSubset<T, WasteEventUpsertArgs<ExtArgs>>): Prisma.Prisma__WasteEventClient<runtime.Types.Result.GetResult<Prisma.$WasteEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WasteEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WasteEventCountArgs} args - Arguments to filter WasteEvents to count.
   * @example
   * // Count the number of WasteEvents
   * const count = await prisma.wasteEvent.count({
   *   where: {
   *     // ... the filter for the WasteEvents we want to count
   *   }
   * })
  **/
  count<T extends WasteEventCountArgs>(
    args?: Prisma.Subset<T, WasteEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WasteEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WasteEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WasteEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WasteEventAggregateArgs>(args: Prisma.Subset<T, WasteEventAggregateArgs>): Prisma.PrismaPromise<GetWasteEventAggregateType<T>>

  /**
   * Group by WasteEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WasteEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WasteEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WasteEventGroupByArgs['orderBy'] }
      : { orderBy?: WasteEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WasteEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWasteEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WasteEvent model
 */
readonly fields: WasteEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WasteEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WasteEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  device<T extends Prisma.DeviceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DeviceDefaultArgs<ExtArgs>>): Prisma.Prisma__DeviceClient<runtime.Types.Result.GetResult<Prisma.$DevicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WasteEvent model
 */
export interface WasteEventFieldRefs {
  readonly id: Prisma.FieldRef<"WasteEvent", 'String'>
  readonly deviceId: Prisma.FieldRef<"WasteEvent", 'String'>
  readonly wasteType: Prisma.FieldRef<"WasteEvent", 'WasteType'>
  readonly moistureValue: Prisma.FieldRef<"WasteEvent", 'Float'>
  readonly detectedAt: Prisma.FieldRef<"WasteEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * WasteEvent findUnique
 */
export type WasteEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WasteEvent
   */
  select?: Prisma.WasteEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WasteEvent
   */
  omit?: Prisma.WasteEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WasteEventInclude<ExtArgs> | null
  /**
   * Filter, which WasteEvent to fetch.
   */
  where: Prisma.WasteEventWhereUniqueInput
}

/**
 * WasteEvent findUniqueOrThrow
 */
export type WasteEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WasteEvent
   */
  select?: Prisma.WasteEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WasteEvent
   */
  omit?: Prisma.WasteEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WasteEventInclude<ExtArgs> | null
  /**
   * Filter, which WasteEvent to fetch.
   */
  where: Prisma.WasteEventWhereUniqueInput
}

/**
 * WasteEvent findFirst
 */
export type WasteEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WasteEvent
   */
  select?: Prisma.WasteEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WasteEvent
   */
  omit?: Prisma.WasteEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WasteEventInclude<ExtArgs> | null
  /**
   * Filter, which WasteEvent to fetch.
   */
  where?: Prisma.WasteEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WasteEvents to fetch.
   */
  orderBy?: Prisma.WasteEventOrderByWithRelationInput | Prisma.WasteEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WasteEvents.
   */
  cursor?: Prisma.WasteEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WasteEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WasteEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WasteEvents.
   */
  distinct?: Prisma.WasteEventScalarFieldEnum | Prisma.WasteEventScalarFieldEnum[]
}

/**
 * WasteEvent findFirstOrThrow
 */
export type WasteEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WasteEvent
   */
  select?: Prisma.WasteEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WasteEvent
   */
  omit?: Prisma.WasteEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WasteEventInclude<ExtArgs> | null
  /**
   * Filter, which WasteEvent to fetch.
   */
  where?: Prisma.WasteEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WasteEvents to fetch.
   */
  orderBy?: Prisma.WasteEventOrderByWithRelationInput | Prisma.WasteEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WasteEvents.
   */
  cursor?: Prisma.WasteEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WasteEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WasteEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WasteEvents.
   */
  distinct?: Prisma.WasteEventScalarFieldEnum | Prisma.WasteEventScalarFieldEnum[]
}

/**
 * WasteEvent findMany
 */
export type WasteEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WasteEvent
   */
  select?: Prisma.WasteEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WasteEvent
   */
  omit?: Prisma.WasteEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WasteEventInclude<ExtArgs> | null
  /**
   * Filter, which WasteEvents to fetch.
   */
  where?: Prisma.WasteEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WasteEvents to fetch.
   */
  orderBy?: Prisma.WasteEventOrderByWithRelationInput | Prisma.WasteEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WasteEvents.
   */
  cursor?: Prisma.WasteEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WasteEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WasteEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WasteEvents.
   */
  distinct?: Prisma.WasteEventScalarFieldEnum | Prisma.WasteEventScalarFieldEnum[]
}

/**
 * WasteEvent create
 */
export type WasteEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WasteEvent
   */
  select?: Prisma.WasteEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WasteEvent
   */
  omit?: Prisma.WasteEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WasteEventInclude<ExtArgs> | null
  /**
   * The data needed to create a WasteEvent.
   */
  data: Prisma.XOR<Prisma.WasteEventCreateInput, Prisma.WasteEventUncheckedCreateInput>
}

/**
 * WasteEvent createMany
 */
export type WasteEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WasteEvents.
   */
  data: Prisma.WasteEventCreateManyInput | Prisma.WasteEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WasteEvent update
 */
export type WasteEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WasteEvent
   */
  select?: Prisma.WasteEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WasteEvent
   */
  omit?: Prisma.WasteEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WasteEventInclude<ExtArgs> | null
  /**
   * The data needed to update a WasteEvent.
   */
  data: Prisma.XOR<Prisma.WasteEventUpdateInput, Prisma.WasteEventUncheckedUpdateInput>
  /**
   * Choose, which WasteEvent to update.
   */
  where: Prisma.WasteEventWhereUniqueInput
}

/**
 * WasteEvent updateMany
 */
export type WasteEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WasteEvents.
   */
  data: Prisma.XOR<Prisma.WasteEventUpdateManyMutationInput, Prisma.WasteEventUncheckedUpdateManyInput>
  /**
   * Filter which WasteEvents to update
   */
  where?: Prisma.WasteEventWhereInput
  /**
   * Limit how many WasteEvents to update.
   */
  limit?: number
}

/**
 * WasteEvent upsert
 */
export type WasteEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WasteEvent
   */
  select?: Prisma.WasteEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WasteEvent
   */
  omit?: Prisma.WasteEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WasteEventInclude<ExtArgs> | null
  /**
   * The filter to search for the WasteEvent to update in case it exists.
   */
  where: Prisma.WasteEventWhereUniqueInput
  /**
   * In case the WasteEvent found by the `where` argument doesn't exist, create a new WasteEvent with this data.
   */
  create: Prisma.XOR<Prisma.WasteEventCreateInput, Prisma.WasteEventUncheckedCreateInput>
  /**
   * In case the WasteEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WasteEventUpdateInput, Prisma.WasteEventUncheckedUpdateInput>
}

/**
 * WasteEvent delete
 */
export type WasteEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WasteEvent
   */
  select?: Prisma.WasteEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WasteEvent
   */
  omit?: Prisma.WasteEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WasteEventInclude<ExtArgs> | null
  /**
   * Filter which WasteEvent to delete.
   */
  where: Prisma.WasteEventWhereUniqueInput
}

/**
 * WasteEvent deleteMany
 */
export type WasteEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WasteEvents to delete
   */
  where?: Prisma.WasteEventWhereInput
  /**
   * Limit how many WasteEvents to delete.
   */
  limit?: number
}

/**
 * WasteEvent without action
 */
export type WasteEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WasteEvent
   */
  select?: Prisma.WasteEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WasteEvent
   */
  omit?: Prisma.WasteEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WasteEventInclude<ExtArgs> | null
}
